### PR TITLE
Set Default Proof Using should not be recognised by isProofStart

### LINKED ISSUE #12: "Set Suggest Proof Using" and "Set Default Proof Using " are mistaken for proofs
Folded:
image

Unfolded:
image

### PR DESCRIPTION
**Pull request by yforster**
Before:

image

After:

image

### CODE REVIEW

**Comment by chdoc** [comment]
Nice catch. 

fixes #12

**Comment by chdoc** [comment]
@yforster Can you please also take care of `Set Suggest Proof Using` as mentioned in #12.

**Comment by yforster** [comment]
Oh, I didn't see that there is already an issue about this. Now `Suggest Proof Using` should also not be recognised.

**Review by liyishuai — APPROVED** [review]
LGTM. Propose merging this week if no concerns arise.

#13 will add an `example` directory to the repo. Maybe worth showcasing the screenshot code within the examples?

**Pull request merged**
