### PR TITLE
restructure: use as subfolder (#10)

### PR DESCRIPTION
**Pull request by chdoc**
I just realized that #10 was not merged to master but to a separate branch. I think it is not a good idea to maintain two structurally different branches of coqdocjs. What would it take to merge this into master?

My suggestion would be to:

- [x] make copying of the resources the default, as documentation is frequently copied elsewhere (e.g, `gh-pages`)
- [x] replace the `Makefile.doc` with a `Makefile.coq.local` along the lines of what i did on [this branch of reglang](https://github.com/coq-community/reglang/tree/coqdocjs-module)

CC: @palmskog @liyishuai

### CODE REVIEW

**Comment by liyishuai** [comment]
Yes we should merge to master.
`Makefile.coq.local` sounds better than the current `Makefile.doc`.
Copying by default seems reasonable. I can foresee usages of symlink on gh-pages that saves spaces, but copying is usually more reliable.

**Comment by liyishuai** [comment]
For switching to `Makefile.coq.local`: Does it work with `COQMAKEFILE` other than `Makefile.coq`? If no, should we disable customization for `COQMAKEFILE`?

**Comment by chdoc** [comment]
> For switching to `Makefile.coq.local`: Does it work with `COQMAKEFILE` other than `Makefile.coq`? If no, should we disable customization for `COQMAKEFILE`?

If you generate Makefile.coq with the usual `coq_makefile -f _CoqProject -o Makefile.coq` then it contains a `-include Makefile.coq.local` directive. However, if you replace `Makefile.coq` with anything else (e.g., -o Foo) the include directive is adapted acorgingly (e.g., -include Foo.local). 

I think it would be nice if the `Makefile.coq.local` would work out of the box for the `standard build` used by most coq-community projects where you have a completely generic `Makefile` (that does nothing other than generating `Makefile.coq` and calling its targets) and put your customizations in `Makefile.coq.local`, where one can profit from the variables set in `Makefile.coq`. This might be as simple as copying this [Makefile.coq.local](https://github.com/coq-community/reglang/blob/coqdocjs-module/Makefile.coq.local), which makes no reference to the surrounding project.

**Comment by liyishuai** [comment]
@chdoc Does the current [example](https://github.com/coq-community/coqdocjs/tree/submodule/example) look better?
I kept the name `Makefile.doc` for Makefile-including, and had the users to choose the alias for copying/symlink-ing, e.g. `Makefile.coq.local`.

Propose merging if no concerns arise this week.

**Pull request merged**
